name: JS Integration Test
on:
  pull_request:
    paths:
      - "cypress/**"

jobs:
  run:
    name: Cypress Test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
<<<<<<< HEAD
      - run: yarn test:cypress
=======
      - run: yarn test:cypress -- --spec "cypress/**/*.cypress.js"
      - run: yarn test:playwright .playwright.js
>>>>>>> a4636229be3b4b37edbce94179d899e01a770c2c
